<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon></ApplicationIcon>
    <AssemblyName>KeyboardLangFixer</AssemblyName>
    <RootNamespace>KeyboardLangFixer</RootNamespace>
    <Platforms>x64</Platforms>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\data\en_words.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>data\en_words.txt</Link>
    </None>
    <None Include="..\data\fa_words.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>data\fa_words.txt</Link>
    </None>
  </ItemGroup>

</Project>
